### ISSUE TITLE
Does not conform to hanging brace aesthetic used throughout remainder of project.

### ISSUE THREAD

**Issue by cooley61** [PogopunkXIII/RomanNumeralConverter#1]
https://github.com/PogopunkXIII/RomanNumeralConverter/blob/48a82ce5b8ab82db94fd3bd99c9ef9a2655c6533/src/Program.java#L137

**Comment by PogopunkXIII** [comment]
fixed in commit:
c5147d2a10d4427fec2c587c5b569752dd54dfdb
